services:
  mongodb:
    image: mongo:7
    container_name: mongodb_intern_training
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: intern_training
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: